VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IIndicateur"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public Enum Decision
    acheter = 0
    vendre = 1
    rien = 2
End Enum

Public Sub getArr(arr() As Variant)

End Sub

Public Sub Evaluer(ByVal i As Integer)

End Sub

Public Function Decider(ByVal i As Integer) As Decision

End Function

